// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq4UF4_j6dOVU7uyHZiiMF58v76aO9RBI',
    appId: '1:452185459849:android:aa7afef90e3650b2198a58',
    messagingSenderId: '452185459849',
    projectId: 'cop-cup',
    storageBucket: 'cop-cup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu7rJuPFu-gt26uFhm_s-0A_ECygHKQeg',
    appId: '1:452185459849:ios:f9d04bacaf5bfd2f198a58',
    messagingSenderId: '452185459849',
    projectId: 'cop-cup',
    storageBucket: 'cop-cup.firebasestorage.app',
    androidClientId: '452185459849-i4017s720n6d86cm90orfop6c7u5l3kj.apps.googleusercontent.com',
    iosClientId: '452185459849-bhk9gkrbfl5cvjnnu5c8g0bejba6anit.apps.googleusercontent.com',
    iosBundleId: 'com.ethan.copcup',
  );

}